### ISSUE TITLE
Footnotes (and more) support

### ISSUE THREAD

**Issue by jeffmcneill** [docpad/docpad-plugin-marked#13]
Hello there, would it be possible instead of using Marked, to use https://github.com/markdown-it/markdown-it which seems to have included many handy improvements, especially Footnotes which is required on my projects.

**Comment by kizu** [comment]
That should be a separate plugin, like `docpad-plugin-markdownit`. It would be strange to use a `marked` in this plugin's name, but some other renderer instead :)
