### ISSUE TITLE
Moderate severity security vulnerability detected in marked < 0.3.9

### ISSUE THREAD

**Issue by nylnook** [docpad/docpad-plugin-marked#15]
Hi dear Bevry team,

Github informed me by email this morning there is a moderate severity security vulnerability detected in marked < 0.3.9, in my website ... 
But Docpad in this actual version  (v6.79.4) require docpad-plugin-marked in ~2.4.0 ... 
Maybe it's time for an update ?

thanks for your work !

**Comment by balupton** [comment]
fixed in v2.5.0, thanks!
